version: "3"
services:
  mariadb:
    container_name: "mariadb"
    image: mariadb:10
    restart: always
    ports:
      - 3308:3306
    volumes:
      - "./mariadb/conf.d:/etc/mysql/conf.d"
      - "./mariadb/data:/var/lib/mysql"
    environment:
      MARIADB_DATABASE: nncdb
      MARIADB_USER: nnc
      MARIADB_PASSWORD: abcd1234
      MARIADB_ROOT_PASSWORD: 1111

  redis:
    image: redis
    command: redis-server --port 6379
    container_name: docker_redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379